workspace:
  base: /go
  path: src/github.com/uswitch/certificate-init-container

pipeline:
  build:
    when:
      event: [ push, pull_request ]
    image: golang:1.9
    commands:
      - go test -v ./...
      - CGO_ENABLED=0 go build -o bin/certificate-init-container .

  publish:
    when:
      event: push
      branch: master
    image: plugins/docker
    repo: registry.usw.co/cloud/exporter/certificate-init-container
    tags:
      - latest
      - "${DRONE_COMMIT}"
